  version: "3.9"
  services:
    app:
      image: geolocation_api:1
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWD: password
        POSTGRES_HOST: db
      ports:
        - 3000:3000
    db:
      image: postgres:alpine3.15
      environment:
        POSTGRES_PASSWORD: password